---
title: "Practice 6.2 3.0"
author: "rpp"
date: "2023-10-30"
output: html_document
---

```{r setup}
library(animation)
library(ggplot2)
library (gganimate)


growhw <- function(growth.rateN1, growth.rateN2, plot_N1 = FALSE, plot_N2 = FALSE) {  
  num_gen <- 30
  N1 <- rep(0, num_gen)
  N2 <- rep(0, num_gen)
  generation <- 1:num_gen
  N1[1] <- 1
  N2[1] <- 1
  K1 <- 150
  K2 <- 180
  a12 <- 1.5
  a21 <- 1.5
  
  for (i in 2:num_gen) {
    # N[i]  = N[i-1]+ (growth.rate*N[i-1]*((100-N[i-1])/100)){
    N1[i] = N1[i - 1] + (growth.rateN1 * N1[i - 1] * ((K1 - N1[i - 1] - a12 * N2[i - 1]) / K1))
    N2[i] = N2[i - 1] + (growth.rateN2 * N2[i - 1] * ((K2 - N2[i - 1] - a21 * N2[i - 1]) / K2))
  }
  
  
  if (plot_N1) {
    plot(generation, N1, xlim=c(0,30), ylim=c(0,180), type = 'b', 
         main = paste("Rate =", growth.rateN1, "- N1"), xlab = "Generation", ylab = "N1")
  }
  
  if (plot_N2) {
    plot(generation, N2, xlim=c(0,30), ylim=c(0,180), type = 'b', 
         main = paste("Rate =", growth.rateN2, "- N2"), xlab = "Generation", ylab = "N2", col = "red")

    
  }
}



#plot Species 1 alone
growhw(1,0, plot_N1 = TRUE)
text(4,150,"Species 1 alone")

#plot Species 2 alone, but the population reached saturation before reaching K2
growhw(0,1, plot_N2 = TRUE)
text(4,150,"Species 2 alone")

#plot Both Species competing, but the plot only show one line at a time
growhw(1,1, plot_N1 = TRUE,plot_N2 = TRUE)
text(8,150,"Both Species competing")
