---
title: "Practice 6.2"
author: "rpp"
date: "2023-10-25"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library(animation)
library(ggplot2)
library (gganimate)


growhw <- function(growth.rateN1,growth.rateN2, plot_N1 = FALSE, plot_N2 = FALSE) {
  num_gen <- 30
  N1 <- rep(0, num_gen)
  N2 <- rep(0, num_gen)
  generation <- 1:num_gen
  N1[1] <- 1
  N2[1] <- 1
  K1 <- 100
  K2 <- 120
  a12 <- 1.5
  a21 <- 1.5
  
  for (i in 2:num_gen) {
   # N[i]  = N[i-1]+ (growth.rate*N[i-1]*((100-N[i-1])/100))
    N1[i] = N1[i - 1] + (growth.rateN1 * N1[i - 1] * (100 - (N1[i - 1] - a12 * N2[i - 1]) / 100))
    N2[i] = N2[i - 1] + (growth.rateN2 * N2[i - 1] * (120 - (N2[i - 1] - a21 * N2[i - 1]) / 120))
    
  }
  
  # Set an appropriate y-axis limit range, base on the K value 
  ylim_range <- c(0, 150) 
  
  
  if (plot_N1) {
    plot(generation, N1, xlim=c(0,30), ylim=c(0,150), type = 'b', 
         main = paste("Rate =", growth.rateN1, "- N1"), xlab = "Generation", ylab = "N1")
  }
  
  if (plot_N2) {
    plot(generation, N2, xlim=c(0,30), ylim=c(0,150), type = 'b', 
         main = paste("Rate =", growth.rateN2, "- N2"), xlab = "Generation", ylab = "N2")
    lines(generation, N2, col = "red") 
  }
}


#plot Species 1 alone, but the population didn't reach saturation
growhw(0.003,0, plot_N1 = TRUE)
text(8,140,"Species 1 alone")

#plot Species 2 alone, but the population didn't reach saturation
growhw(0,0.003, plot_N2 = TRUE)
text(8,140,"Species 2 alone")

#plot Both Species competing, but the plot only show one line
#and also the population didn't reach saturation,
growhw(0.005,0.005, plot_N1 = TRUE,plot_N2 = TRUE)
text(8,140,"Both Species competing")



saveGIF({
  for (i in seq(0.01, 0.5, by = 0.01)){
    growhw(i,0, plot_N1 = TRUE)  # 生成 N1 的 GIF
  }
}, movie.name = "N1.gif")

saveGIF({
  for (i in seq(0.1, 0.5, by = 0.01)){
    growhw(0,i, plot_N2 = TRUE)  # 生成 N2 的 GIF
  }
}, movie.name = "N2.gif")

#two lines didn't show at the same time 
saveGIF({
  for (i in seq(0.1, 0.5, by = 0.01)){
    growhw(i,i, plot_N1 = TRUE, plot_N2 = TRUE)
  }
}, movie.name = "N1_and_N2.gif")

